Feat/update ticket
gloedige/TixHive pull request #11
Opened 2023-09-27 14:57 UTC by gloedige

2023-09-27 15:11 UTC, s-gbz reviewed
Super Arbeit!
Ein paar Kleinigkeiten habe ich mal als Denkanstoß kommentiert

2023-09-27 15:11 UTC, s-gbz commented on backend/src/main/java/de/iav/backend/service/TicketService.java
> +        throw new NoSuchElementException("Element with " + ticketId + " not found!");
Die coolen Kids bauen sich dafür eigene Exceptions :P
(Ideenanstoß, keine Notwendigkeit)

2023-09-27 15:11 UTC, s-gbz commented on backend/src/test/java/de/iav/backend/controller/TicketControllerIntegrationTest.java
> +        TicketRequestDTO ticketRequestDTO2 = new TicketRequestDTO(
Der Test wäre ein bisschen leichter zu verstehen, wenn man das z.B. `ticketToUpdate` o.ä. nennen würde

2023-09-27 15:11 UTC, s-gbz commented on backend/src/test/java/de/iav/backend/controller/TicketControllerIntegrationTest.java
> +                .andExpect(MockMvcResultMatchers.jsonPath("$.subject").value("Test Subject2")) // Check the response JSON
Codekommentare sind ja üblicherweise nicht nötig, wenn der Code sich selbst erklärt

2023-09-27 15:11 UTC, s-gbz commented on backend/src/test/java/de/iav/backend/service/TicketServiceTest.java
> +        Ticket ticketToUpdate = new Ticket(
Nur als Idee: Wäre `updatedTicket` nicht vlt eindeutiger?

2023-09-27 15:11 UTC, s-gbz commented on frontend/src/main/java/de/iav/frontend/controller/UpdateTicketController.java
> +        // Find the index of the specified Ticket object in the ChoiceBox.
Schau mal in der Datei das die Kommentare sich erübrigen können

2023-09-27 15:11 UTC, s-gbz commented on frontend/src/main/java/de/iav/frontend/controller/UpdateTicketController.java
> +    public void updateTicketAndSwitchToTicketListScene(ActionEvent event) throws IOException {
Ein paar Leerzeilen könnten die Methode vlt ja ein bisschen mehr Atmen lassen

2023-09-27 15:11 UTC, s-gbz commented on frontend/src/main/java/de/iav/frontend/controller/UpdateTicketController.java
> +        TicketToBeUpdated ticketToBeUpdated = new TicketToBeUpdated(
Ich feier die eindeutige Namensgebung dieser Datenklasse

2023-09-28 09:14 UTC, MoinMarcell requested changes
Code sieht soweit gut aus! Tolle Arbeit! ABER ich kann auf den Update Button klicken ohne ein Ticket ausgewählt zu haben und erhalte dann eine nullpointer exception. Eventuell könntest du den Button erst anzeigen, wenn Tickets in der Liste sind und man auch ein Ticket ausgewählt hat?

2023-09-28 09:16 UTC, s-gbz reviewed
Eine Sache übersehen gestern 🙈

2023-09-28 09:16 UTC, s-gbz commented on backend/src/test/java/de/iav/backend/controller/TicketControllerIntegrationTest.java
> +                .andReturn();
Ich hatte gestern sowohl bei diesen Tests als auch den Unit Tests eine Sache übersehen:

Wenn du prüfst, ob die gegebenen Werte den erwarteten Werten entsprechen, ist es vermutlich noch besser, wenn die Werte direkt aus dem Objekten ausliest. Somit bleibt der Test resilienter, wenn sich die Daten des zu prüfenden Objektes mal ändern sollten + du brauchst weniger Tippen und bist copy-paste sicher!

Lasse ich Mal als Vorschlag stehen :)

2023-09-28 09:34 UTC, MoinMarcell approved these changes
LGTM!

2023-09-28 09:35 UTC, merged