Feat/security
gloedige/TixHive pull request #14
Opened 2023-10-15 12:01 UTC by gloedige

enable security
- login with different roles
- register
- logoff
- see tickets depending on user
- different scenes depending on userrole

2023-10-16 12:37 UTC, s-gbz requested changes
Ouuuuff, ein gigantischer PR, aber er läuft, der Code ist größtenteils sauber und ich applaudiere dir Gerd! 👏 

Ein wenig Anpassungsbedarf habe ich noch feststellen können, siehe die Hinweise.

Ein paar anderweitige Hinweise:
- In der UX argumentiert man mit einer ISO-norm. Erwartbarkeit ist eine der Normen.
Da wir in unserer Gesellschaft von links nach rechts lesen, würde ich erwarten, dass der `add`-Button als erste, ausführbare Aktion ganz links wäre (da hatte ich ihn auch erstmal gesucht bis ich ihn rechts entdeckt habe)
![Bildschirmfoto 2023-10-16 um 13 44 15](https://github.com/gloedige/TixHive/assets/23424538/8c64881b-7cb8-4185-9b71-fe8f530672b0)

- Wie wäre es wenn die Priorität standardmäßig auf "LOW" gesetzt wäre - dann würdest du auch keine Meldung einblenden was schief gelaufen wäre und den Leuten zeigen wozu das Feld dient und auch einen Click sparen
- Im gleichen Zuge, warum dürfen Tickets ohne Titel und Beschreibung angelegt werden?
![Bildschirmfoto 2023-10-16 um 13 49 17](https://github.com/gloedige/TixHive/assets/23424538/e3251b43-d9db-490f-b138-866ca7efa7ac)
- Und: Wozu dient die leere, letzte Spalte?
   - Verstehe das es nicht Teil des PRs ist, aber letztes Mal scheint es durchgerutscht zu sein. Wenn du es nicht jetzt noch bearbeiten willst, gerne Ticket erstellen, vormerken, whatever

2023-10-16 12:37 UTC, s-gbz commented on backend/src/main/java/de/iav/backend/service/TicketService.java
> +    private static final String EXCEPTION_MESSAGE_PART2 = " not found!";
Auch hier, die Nachricht im Exceptionkonstruktor definieren und lediglich den Parameter reingeben

2023-10-16 12:37 UTC, s-gbz commented on backend/src/main/java/de/iav/backend/service/TicketService.java
> +    public TicketService(TicketRepository ticketRepository, AppUserRepository appUserRepository, IdService idService, DateTimeService dateTimeService, UserService userService) {
Auch hier: Lombok?

2023-10-16 12:37 UTC, s-gbz commented on backend/src/main/java/de/iav/backend/service/TicketService.java
> +        throw new NoSuchElementException(EXCEPTION_MESSAGE_PART1 + ticketId + EXCEPTION_MESSAGE_PART2);
Nur das du es mal gesehen hast: Es gibt ne abgefahrene Möglichkeiten den "Syntax Sugar" der Optionals zu verwenden und mit `orElse` & co erlauben auf das "händische" `if` zu verzichten.

Ob das besser ist, steht zur Frage, du brauchst es auch nicht übernehmen, aber so wäre eine mögliche Alterantive:


```java
return ticketRepository.findById(ticketId)
        .map(existingTicket -> new Ticket(
                existingTicket.id(),
                ticketToUpdate.subject(),
                ticketToUpdate.priority(),
                ticketToUpdate.status(),
                ticketToUpdate.text(),
                ticketToUpdate.creatorId(),
                existingTicket.creationDate()
        ))
        .map(ticketRepository::save)
        .orElseThrow(() -> new NoSuchElementException(EXCEPTION_MESSAGE_PART1 + ticketId + EXCEPTION_MESSAGE_PART2));
```

Vlt hast du es noch aus dem React-Vortrag im Kopf: `Map` erstellt in Lambdas neue Kollektionen

2023-10-16 12:37 UTC, s-gbz commented on backend/src/main/java/de/iav/backend/service/TicketService.java
> +        throw new NoSuchElementException(EXCEPTION_MESSAGE_PART1 + ticketId + EXCEPTION_MESSAGE_PART2);
Falls du mehr dazu erfahren möchtest, kannst du ChatGPT ggf mit folgendem Propt fragen:

"Is it possible to make this code more elegant by using the optional syntax sugar?
<dein code hier>"

2023-10-16 12:37 UTC, s-gbz commented on backend/src/main/java/de/iav/backend/service/UserService.java
> +    public UserService(AppUserRepository appUserRepository) {
Lombok hilft gerne (bitte schau im Rest des Codes selber)

2023-10-16 12:37 UTC, s-gbz commented on backend/src/test/java/de/iav/backend/controller/TicketControllerTest.java
>          String responseJson = result.getResponse().getContentAsString();
_Welche_ response ist es denn?
Ich frage weil weiter unten response2 auftaucht - das lässt die Lesbarkeit sinken

2023-10-16 12:37 UTC, s-gbz commented on backend/src/test/java/de/iav/backend/controller/TicketControllerTest.java
> +        Assertions.assertEquals(ticketToUpdateStatus.status(), ticketWithUpdatedStatus.status());
Vlt könnte es tatsächlich etwas prägnanter sein die `andExpect`-Syntax zu nutzen, aber das nur Impuls (das ist auch fein, wenn die Variablennamen stimmen)

2023-10-16 12:37 UTC, s-gbz commented on backend/src/test/java/de/iav/backend/controller/TicketControllerTest.java
> +        String UserEmail = "UserEmail";
* `userEmail`

2023-10-16 12:37 UTC, s-gbz commented on backend/src/test/java/de/iav/backend/controller/TicketControllerTest.java
>          String responseJson = result.getResponse().getContentAsString();
Schau diesbezüglich bitte auch mal bei den anderen Tests, ob sich das nicht klarifzieren lässt

2023-10-16 12:37 UTC, s-gbz commented on frontend/src/main/java/de/iav/frontend/model/AppUser.java
> +        List<Ticket> tickets
Die Mongo-Annotationen brauchen wir im FE nicht

2023-10-16 12:37 UTC, s-gbz commented on frontend/src/main/java/de/iav/frontend/model/AppUser.java
> +        List<Ticket> tickets
Wenn diese drin sind, solltest du auch in den Abhängigkeiten schauen, ob nicht etwas reingerutscht ist, dass du gar nicht brauchst iM FE

2023-10-16 15:06 UTC, gloedige commented on backend/src/main/java/de/iav/backend/security/AppUserService.java
> +                .orElseThrow(() -> new UsernameNotFoundException("user not found!"));
diese Exception kommt aus spring security und kann NICHT editiert werden.

2023-10-18 07:43 UTC, s-gbz reviewed
Hey Gerd soweit ich sehe sind noch ein paar Punkte offen
- Test Abhängigkeit
- Kommentare (z.B. AuthController) - am besten mal auf GitHub mit cmd+f nach "//" suchen
- Variablenname *userEmail

Aber, das ist ja jetzt fix gemacht - Endspurt, dran bleiben, bist fast am Ziel! 🙌 🏁

2023-10-18 07:43 UTC, s-gbz commented on backend/src/test/java/de/iav/backend/controller/TicketControllerTest.java
> +        String UserEmail = "userEmail";
```java
        String UserEmail = "userEmail"; 
```
->
```java
        String userEmail = "userEmail"; ->
```
Haha es es ging nicht um den String sondern um den Variablennamen 🙈

2023-10-18 14:09 UTC, merged